spring.config.import=optional:dotenv:/.env

spring.application.name=virtual-wallet-server

spring.datasource.url=${POSTGRESQL_URL}
spring.datasource.username=${POSTGRESQL_USERNAME}
spring.datasource.password=${POSTGRESQL_PASSWORD}
server.port=${PORT:8080}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=0e572cc68748b219f8c7d0d580f851efc2402227c3ccd8443148be2b211ebdf1
jwt.expiration=3600000
